CREATE USER test WITH PASSWORD 'debian';
GRANT ALL PRIVILEGES ON DATABASE climb to test;
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO test;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO www;